version: '3.9'

services:
  backend:
    build: .
    ports:
    - 8000:8000
    volumes:
    - .:/app

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: armenat
      MYSQL_DATABASE: cybersprout

    ports:
    - 3306:3306
    volumes:
    - ./storage/dbdata:/var/lib/mysql
    restart: on-failure

  redis:
    image: redis
    ports:
      - 6379:6379
